config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :rule_sets

  map.resources :rule_sets

  map.resources :rules
  map.resources :rule_templates
  map.root :controller => "rule_sets"

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/rule_set.rb
class RuleSet < ActiveRecord::Base
  has_many :rules, :order => "position ASC"

  def conditions
    c = [[]]
    rules.each do |rule|
      rule_condition = rule.to_conditions
      c[0] << "(#{rule_condition[0]})"
      c << rule_condition[1..-1]
    end
    [c[0].join(" AND "), c[1..-1]].flatten
  end
end

app/controllers/rule_sets_controller.rb
class RuleSetsController < ApplicationController
  # GET /rule_sets
  # GET /rule_sets.xml
  def index
    @rule_sets = RuleSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rule_sets }
    end
  end

  # GET /rule_sets/1
  # GET /rule_sets/1.xml
  def show
    @rule_set = RuleSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rule_set }
    end
  end

  # GET /rule_sets/new
  # GET /rule_sets/new.xml
  def new
    @rule_set = RuleSet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rule_set }
    end
  end

  # GET /rule_sets/1/edit
  def edit
    @rule_set = RuleSet.find(params[:id])
  end

  # POST /rule_sets
  # POST /rule_sets.xml
  def create
    @rule_set = RuleSet.new(params[:rule_set])

    respond_to do |format|
      if @rule_set.save
        flash[:notice] = 'RuleSet was successfully created.'
        format.html { redirect_to(@rule_set) }
        format.xml  { render :xml => @rule_set, :status => :created, :location => @rule_set }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rule_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rule_sets/1
  # PUT /rule_sets/1.xml
  def update
    @rule_set = RuleSet.find(params[:id])

    respond_to do |format|
      if @rule_set.update_attributes(params[:rule_set])
        flash[:notice] = 'RuleSet was successfully updated.'
        format.html { redirect_to(@rule_set) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rule_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rule_sets/1
  # DELETE /rule_sets/1.xml
  def destroy
    @rule_set = RuleSet.find(params[:id])
    @rule_set.destroy

    respond_to do |format|
      format.html { redirect_to(rule_sets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/rule_sets_helper.rb
module RuleSetsHelper
end

app/views/rule_sets/edit.html.erb
<h1>Editing Rule Set</h1>

<% form_for(@rule_set) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <% @rule_set.rules.each_with_index do |rule,i| %>
    <%= check_box_tag "rule_set[rule_ids][]", rule.id, :checked => true %> <%=h rule.name %><br />
  <% end %>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<div id="footer">
  <%= link_to 'Show', @rule_set %>
  <%= link_to 'Back', rule_sets_path %>
</div>

app/views/rule_sets/index.html.erb
<h1>Rule Sets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Rules</th>
    <th colspan="2">Actions</th>
  </tr>

<% @rule_sets.each do |rule_set| %>
  <tr>
    <td><%= link_to h(rule_set.name), rule_set %></td>
    <td><%=h rule_set.rules.size %></td>
    <td><%= link_to 'Edit', edit_rule_set_path(rule_set) %></td>
    <td><%= link_to 'Destroy', rule_set, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<div id="footer">
  <%= link_to 'New rule set', new_rule_set_path %>
</div>

app/views/rule_sets/new.html.erb
<h1>New rule_set</h1>

<% form_for(@rule_set) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit 'Create' %> Next: add a rule
  </p>
<% end %>

<div id="footer">
<%= link_to 'Back', rule_sets_path %>
</div>

app/views/rule_sets/show.html.erb
<h2>
  <b>Name:</b>
  <%=h @rule_set.name %>
</h2>

<h3>Rules</h3>
<table>
<% @rule_set.rules.each do |rule| %>
  <tr>
    <td><%= link_to h(rule.name), rule %></td>
  </tr>
<% end %>
</table>

<h3>SQL</h3>
<pre><code><%= @rule_set.conditions.inspect %></code></pre>

<div style="background-color: #eef;width:200px;margin: 20px 0; padding: 5px">
  <% @rule = @rule_set.rules.build %>
  <%= render :partial => "rules/new" %>
</div>

<div id="footer">
<%= link_to 'Edit', edit_rule_set_path(@rule_set) %> |
<%= link_to 'Back', rule_sets_path %>
</div>